### ISSUE TITLE
Addition of True Rounded Corners

### ISSUE THREAD

**Issue by sametaor** [z1nc0r3/CircleDarkBlur.Flow-Launcher#1]
## Description
Hi, I recently came across this awesome theme and went ahead and installed it. Everything was going smoothly until my so-called "OCD" took notice of a weird box that was covering the background of flow launcher. I guessed it was probably for adding the blur behind it, but is it possible to also round off the blurred background, just like the rounded corners of the foreground? I saw a few themes which also faced a similar issue, except a few.

## Steps to Reproduce
1. Install flow launcher
2. Install CircleDarkBlur from this repo
3. Apply theme in Flow Launcher settings
4. Open Flow Launcher multiple times to check.
### Expected Behaviour
Flow launcher should have proper rounded corners, both in the foreground and background.
### Actual Behaviour
Flow launcher does not have rounded corners for the background (blur).

## Image Reference
![image](https://github.com/user-attachments/assets/17d86a13-7b08-49f2-932e-515f3ddc0f5a)

**Comment by z1nc0r3** [comment]
Hi @sametaor, thank you for using my theme. 

However, this issue is related to the WPF UI framework (afaik). You can see a conversation already happened in the [theme discussion](https://github.com/Flow-Launcher/Flow.Launcher/discussions/1438#discussioncomment-4558997) itself. I checked a few inbuilt themes with the blur effect (yes, this issue is due to the blue effect) and found that those also have this issue.

I tried to find a solution to this issue some time ago but was unsuccessful. Maybe it will be fixed in the future so I'll keep the issue open for now. If you find any blur themes without this issue, please share them. Thanks!

**Comment by sametaor** [comment]
> Hi @sametaor, thank you for using my theme. 
> 
> However, this issue is related to the WPF UI framework (afaik). You can see a conversation already happened in the [theme discussion](https://github.com/Flow-Launcher/Flow.Launcher/discussions/1438#discussioncomment-4558997) itself. I checked a few inbuilt themes with the blur effect (yes, this issue is due to the blue effect) and found that those also have this issue.
> 
> I tried to find a solution to this issue some time ago but was unsuccessful. Maybe it will be fixed in the future so I'll keep the issue open for now. If you find any blur themes without this issue, please share them. Thanks!

Thanks a lot for the response! A few themes I also installed that do not have this issue, aside from the pre-installed ones are Violet, macOS and AlfredBlue.

**Comment by z1nc0r3** [comment]
I just tested those themes (macOS, Violet & AlfredBlue) and think they also have this issue. I've included the screenshots for reference. Could you please confirm whether you can reproduce this? I think the visibility of the edges varies with the theme's background color.

macOS
![image](https://github.com/user-attachments/assets/0b963d53-154e-4311-854e-76789dc825ce)

Violet
![image](https://github.com/user-attachments/assets/e02155b5-e165-45b9-9671-10ad875cc428)

The AlfredBlue theme was not blurred theme so it doesn't have this issue.

**Comment by sametaor** [comment]
I can confirm the issue does persist on these themes as well. I also happened to notice on the onsetglaze theme's issues page that somebody suggested using micaforeveryone's workaround to add rounded corners to flow launcher. Let me see if that makes any changes.

**Comment by sametaor** [comment]
> I can confirm the issue does persist on these themes as well. I also happened to notice on the onsetglaze theme's issues page that somebody suggested using micaforeveryone's workaround to add rounded corners to flow launcher. Let me see if that makes any changes.

Right, the corners disappear as expected as long as Flow Launcher is added as a process under MicaforEveryone, as seen below:
### With MicaforEveryone
![image](https://github.com/user-attachments/assets/f6135a75-3bcb-4c69-8236-e5760762df5b)
### Without MicaforEveryone
![image](https://github.com/user-attachments/assets/0ff5301f-e94d-459c-a15b-3d38980559a4)

Just in case there is a duplicate issue, perhaps this workaround can be mentioned later on until it is fixed natively 👍
Thanks for your time!

**Comment by z1nc0r3** [comment]
That is a really interesting thing to know. Thanks @sametaor. 
Hope this doesn't affect the performance of FL btw

**Comment by sametaor** [comment]
> That is a really interesting thing to know. Thanks @sametaor. Hope this doesn't affect the performance of FL btw

No worries about performance really. It takes almost 14 MB, if we don't take flow launcher's own memory usage itself into account.
